# Generated by Django 6.0.2 on 2026-02-20 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name (e.g. liok-resort-kerala)', unique=True)),
                ('overview', models.TextField(help_text='Full description of the property')),
                ('address', models.CharField(max_length=255)),
                ('map_embed_code', models.TextField(blank=True, help_text='Paste the Google Maps HTML embed code here')),
                ('whatsapp_number', models.CharField(help_text='Number for the direct booking button (e.g. +919876543210)', max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('cover_image', models.ImageField(upload_to='properties/covers/')),
                ('amenities_list', models.TextField(help_text='List amenities separated by commas (e.g. Wifi, Pool, Spa, Parking)')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Deluxe Suite, Ocean View Villa', max_length=100)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price in your currency', max_digits=10)),
                ('max_occupancy', models.IntegerField(default=2)),
                ('image', models.ImageField(upload_to='properties/rooms/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='liok_hotels_app.property')),
            ],
        ),
    ]
