# Generated by Django 6.0.2 on 2026-02-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liok_hotels_app', '0002_blog_category_contactmessage_bookinginquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5, help_text='Rating from 1 to 5'),
        ),
    ]
