# Generated by Django 6.0.2 on 2026-02-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liok_hotels_app', '0003_testimonial_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
