# Generated by Django 6.0.2 on 2026-02-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liok_hotels_app', '0005_property_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='property',
        ),
    ]
