# Generated by Django 6.0.2 on 2026-02-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liok_hotels_app', '0006_remove_galleryimage_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='property',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='rating',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(help_text='Name of the person giving the testimonial', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='review',
            field=models.TextField(help_text='Customer or client review'),
        ),
    ]
