# Generated by Django 6.0.2 on 2026-02-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liok_hotels_app', '0007_remove_testimonial_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the room category'),
        ),
    ]
