# Generated by Django 6.0.2 on 2026-02-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liok_hotels_app', '0008_alter_roomcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginquiry',
            name='room_category',
            field=models.CharField(blank=True, help_text='The type of room selected by the guest', max_length=100, null=True),
        ),
    ]
