# Generated by Django 6.0.2 on 2026-03-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liok_hotels_app', '0009_bookinginquiry_room_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginquiry',
            name='guests',
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='children_13_plus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='children_8_12',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
