# Generated by Django 6.0.2 on 2026-03-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liok_hotels_app', '0010_remove_bookinginquiry_guests_bookinginquiry_adults_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginquiry',
            name='children_13_plus',
        ),
    ]
